name: Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint black
        pip install pr-agent
        
    - name: Run pylint
      run: |
        pylint --rcfile=services/agent/.pylintrc --ignore-imports=yes services/agent/src/pr_agent_lambda/*.py
        
    - name: Run black
      run: |
        black --check services/agent/src/pr_agent_lambda/*.py 